#!/bin/bash -eu

getList() {
  curl -s 'https://api.github.com/users/jobscale/repos?type=all&sort=updated&page=1' | grep clone_url | awk -F'"' '{print $4}' | awk -F'[/.]' '{print $6}' > list-repos
  curl -s 'https://api.github.com/users/jobscale/repos?type=all&sort=updated&page=2' | grep clone_url | awk -F'"' '{print $4}' | awk -F'[/.]' '{print $6}' >> list-repos
  curl -s 'https://api.github.com/users/jobscale/repos?type=all&sort=updated&page=3' | grep clone_url | awk -F'"' '{print $4}' | awk -F'[/.]' '{print $6}' >> list-repos  
  cat list-repos
}
clone() {
  [[ ! -d $1 ]] && git clone https://github.com/jobscale/$1.git
}
cloneAll() {
  list=($(getList))
  for name in ${list[*]}
  do
    clone $name
  done
}
allBytes() {
  list=($(ls -1d */))
  mkdir .swap-tmp
  for name in ${list[@]}
  do
    mv $name.git .swap-tmp
    du -s $name
    mv .swap-tmp/.git $name.git
  done
  rmdir .swap-tmp
}
diffAll() {
  list=($(ls -1d */))
  for name in ${list[@]}
  do
    cd $name
    echo $name
    git diff
    cd - >& /dev/null
  done
}
echo '[Usage]:'
echo 'cloneAll'
echo 'getList'
echo 'clone nginx'
echo 'allBytes'
echo 'diffAll'
