#!/bin/bash

db() {
  apt install -y mariadb-server
}

cli() {
  apt install -y \
    curl whois nmap traceroute net-tools \
    nfs-common cifs-utils exfat-utils sshfs \
    git subversion vim tmux dstat peco \
    at expect zip unzip colordiff speedtest-cli \
    mariadb-client libpng-dev nasm
}

account() {
  user=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  echo "$user ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
}

system() {
  dd if=/dev/zero of=/mnt/swap bs=2M count=512
  chmod 0600 /mnt/swap
  mkswap /mnt/swap
  swapon /mnt/swap
  echo '/mnt/swap none swap sw 0 0' | tee -a /etc/fstab
}

main() {
  date +'START    my-init %Y-%m-%d %H:%M:%S'
  db
  account
  system
  cli
  date +'FINISHED my-init %Y-%m-%d %H:%M:%S'
}

main | tee -a /var/log/cloud-my-init.log

