#!/bin/bash

web() {
    apt install -y $(apt search php | grep "^php7" | grep -v snmp | awk -F'/' '{print $1}' | xargs) nginx nginx-extras
    rm -f /etc/nginx/sites-enabled/default
    cp -pr /var/site/projects/_/conf.d /etc/nginx
    ln -s /run/php/php7*sock /run/php/php-fpm.sock
    chown -R www-data. /var/log/nginx
    systemctl restart nginx
}

account() {
    usermod -l jobscale -m -d /home/jobscale ubuntu
    ln -s /var/site/cloud/land.pem /home/jobscale/.ssh/id_rsa
    echo 'jobscale ALL=(ALL) NOPASSWD:ALL' | tee -a /etc/sudoers.d/70-users
    systemctl restart sshd
}

system() {
    dd if=/dev/zero of=/mnt/swap bs=1M count=1024
    chmod 0600 /mnt/swap
    mkswap /mnt/swap
    swapon /mnt/swap
    echo '/mnt/swap swap swap defaults 0 0' | tee -a /etc/fstab
}

main() {
    date +'START    my-init %Y-%m-%d %H:%M:%S'
    web
    account
    system
    date +'FINISHED my-init %Y-%m-%d %H:%M:%S'
}

main | tee -a /var/log/cloud-my-init.log

