#!/bin/bash -eu

mkdir -p /var/www/html
echo '<?php
  $x = 0.0001;
  for ($i = 0; $i < 100000; $i++) {
    $x += sqrt($x);
  }
  echo "OK ";' > /var/www/html/index.php
# echo '<?php system("timeout 1 openssl speed -multi $(grep processor /proc/cpuinfo | wc -l)");' > /var/www/html/index.php
unlink /etc/nginx/sites-enabled/default
rm -fr /etc/nginx/conf.d
ln -sfn /root/nginx.conf.d /etc/nginx/conf.d

