#!/bin/bash -eu

netInit() {
  rm /etc/resolv.conf
  ln -sfn /run/systemd/resolve/resolv.conf /etc/resolv.conf
}
account() {
  user=jobscale
  old=$(grep -w 1000 /etc/passwd | awk -F: '{print $1}')
  usermod -l $user -m -d /home/$user $old
  echo "$user ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/70-users
  systemctl restart sshd
}
main() {
  date +'BEGIN $0 user-data %Y-%m-%d %H:%M:%S'
  netInit
  account
  date +'END   $0 user-data %Y-%m-%d %H:%M:%S'
}
main
