#!/bin/bash

netInit() {
    sudo ln -sfn /run/systemd/resolve/resolv.conf /etc/resolv.conf
}

fsInit() {
    apt update
# can't automatically   apt dist-upgrade -y
    apt install -y nfs-common
    mkdir -p /mnt/sdb
    echo "fs-f4a8113d.efs.eu-west-1.amazonaws.com:/ /mnt/sdb nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,soft,intr,timeo=4,retrans=1 0 0" | tee -a /etc/fstab
    mount -a
    mount -v
    ln -s /mnt/sdb/site /var
}

main() {
    date +'BEGIN $0 user-data %Y-%m-%d %H:%M:%S'
    time netInit
    time fsInit
    if [ -x /var/site/cloud/init ]
    then
        time /var/site/cloud/init
    fi
    date +'END   $0 user-data %Y-%m-%d %H:%M:%S'
}

main

