#!/bin/bash -eu

alias sudo='sudo -E'
export DEBIAN_FRONTEND=noninteractive
main() {
  sudo apt update
  sudo apt upgrade -y
  sudo apt install -y python3 python3-pip unzip zip \
    docker.io curl vim tmux git net-tools dnsutils
  sudo usermod -aG docker $(whoami)
  pip3 install awscli awslogs --user
}
main
