#!/bin/bash -eu

alias sudo='sudo -E'
export DEBIAN_FRONTEND=noninteractive
sudo apt update
sudo apt upgrade -y
sudo apt install -y python python-pip python3 python3-pip zip
pip3 install awscli awslogs --user
