#!/usr/bin/env bash
set -eu

main() {
  apt -y install certbot
  certbot --rsa-key-size 4096 --no-bootstrap certonly --manual --manual-public-ip-logging-ok -d jsx.jp -d *.jsx.jp -d *.in.jsx.jp --preferred-challenges dns --agree-tos --register-unsafely-without-email
  cd /etc/letsencrypt/live
  rm $(find . -name README)
  zip -r /etc/nginx/tls *
  echo "Created - $(ls -lh /etc/nginx/tls.zip)"
}

main
