#!/usr/bin/env bash

set -eu

main() {
  for i in {9..0}
  do
    sleep 2
    [[ "$(nc partner 443 -v -w 1 < /dev/null 2>&1 | grep -e succeeded -e open | wc -l)" != 0 ]] && return 0
    echo -n $i..
  done
  echo " connection failed."
  return 1
}

main
