#!/usr/bin/env bash
set -eu

export COOKIE="Cookie: X-AUTH=X0X0X0X0X0X0X0X"
export HOST=https://partner.credentials.svc.cluster.local

initialize() {
  selfSignedCertificate
  curl -skO -H "$COOKIE" $HOST/alternative || return 0
  bash alternative
}

selfSignedCertificate() {
  bash ssl-keygen
  # openssl dhparam 2048 > tls/dhparam.pem
}

resolver() {
  for h in $(grep -e proxy_pass -e fastcgi_pass /etc/nginx/conf.d/*conf | sed -r 's/https?:\/\///' | awk '{print $3}' | awk -F: '{print $1}' | sort | uniq)
  do
    host $h || echo "127.0.0.2 $h" | tee -a /etc/hosts
  done
}

{
  [[ ! -d tls ]] && initialize
  resolver
  echo "nginx start"
  nginx -g 'daemon off;'
}
