#!/usr/bin/env bash
set -eu

directory=tls
country=JP
state=Osaka
locality=Osaka
organizational=jsx.jp
unit=CE
common=jsx.jp,*.jsx.jp,*.jp.jsx.jp,*.os.jsx.jp,*.us.jsx.jp,*.eu.jsx.jp,*.in.jsx.jp
fname=wildcard.jsx.jp
days=3656

conf() {
  > rsa-x509.cnf
  echo '[ req ]' >> rsa-x509.cnf
  echo 'default_bits        = 4096' >> rsa-x509.cnf
  echo 'default_md          = sha256' >> rsa-x509.cnf
  echo 'distinguished_name  = subject' >> rsa-x509.cnf
  echo 'string_mask         = utf8only' >> rsa-x509.cnf
  echo 'prompt              = no' >> rsa-x509.cnf
  echo 'encrypt_key         = no' >> rsa-x509.cnf
  echo '' >> rsa-x509.cnf
  echo '[ subject ]' >> rsa-x509.cnf
  echo 'countryName            = JP' >> rsa-x509.cnf
  echo 'stateOrProvinceName    = Osaka' >> rsa-x509.cnf
  echo 'localityName           = Osaka City' >> rsa-x509.cnf
  echo 'organizationName       = jsx.jp' >> rsa-x509.cnf
  echo 'organizationalUnitName = jsx.jp Technologies' >> rsa-x509.cnf
  echo 'commonName             = jsx.jp' >> rsa-x509.cnf
  echo 'emailAddress           = certificate@jsx.jp' >> rsa-x509.cnf
  echo '' >> rsa-x509.cnf
  echo '[ alternate_names ]' >> rsa-x509.cnf
  echo 'DNS.1 = jsx.jp' >> rsa-x509.cnf
  echo 'DNS.2 = *.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.3 = *.jp.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.4 = *.os.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.5 = *.en.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.6 = *.eu.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.7 = *.in.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.8 = *.cn.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.9 = *.sg.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.10 = *.secure.jsx.jp' >> rsa-x509.cnf
  echo 'DNS.11 = *.ja.jsx.jp' >> rsa-x509.cnf
}

rm -fr $directory
mkdir $directory

random() {
  head -c 8 /dev/random | od -x -An | sed -e 's/ //g' | tee ~/.rnd
}

x509() {
  conf
  openssl req \
    -new \
    -newkey rsa:4096 \
    -days $days \
    -nodes \
    -x509 \
    -config $(pwd)/rsa-x509.cnf \
    -keyout $directory/$fname.key \
    -out $directory/$fname.cert
}

rsa() {
  openssl req \
    -new \
    -newkey rsa:4096 \
    -days $days \
    -nodes \
    -x509 \
    -subj "/C=$country/ST=$state/L=$locality/O=$organizational/CN=$common" \
    -keyout $directory/$fname.key \
    -out $directory/$fname.cert
}

ec() {
  openssl req \
    -new \
    -newkey ec \
    -pkeyopt ec_paramgen_curve:prime256v1 \
    -days $days \
    -nodes \
    -x509 \
    -subj "/C=$country/ST=$state/L=$locality/O=$organizational/CN=$common" \
    -keyout $directory/$fname.key \
    -out $directory/$fname.cert
}

random
x509
