#!/bin/bash -eu

linkDot() {
  for i in .[a-z]*
  do
    echo $i
    rm -f ~/$i
    ln -fns $(pwd)/$i ~
  done
}

cloneVim() {
  [ -s "$HOME/.vim/bundle/Vundle.vim" ] && return
  git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  vim +PluginInstall +qall
}

cloneTSSL() {
  [ -s "$HOME/.bin/testssl.sh" ] && return
  git clone --depth 1 https://github.com/drwetter/testssl.sh.git "$HOME/.bin/testssl.sh"
}

main () {
  linkDot
  cloneVim
  cloneTSSL
}

main
