#!/bin/bash -eu

for i in .[a-z]*
do
  echo $i
  rm -f ~/$i
  ln -fns $(pwd)/$i ~
done

sudo -E apt update
sudo -E apt install -y vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
