#!/bin/bash -eu

. inst iPhpWeb

if [[ "$PORT" == "" ]]
then
  PORT=80
fi

unlink /etc/nginx/sites-enabled/default
ln -sfn /root/nginx.conf.d /etc/nginx/conf.d
sed -e "s/80/$PORT/" nginx.conf.d/default.conf
spec() {
  echo '<?php
    $x = 0.0001;
    for ($i = 0; $i < 100000; $i++) {
      $x += sqrt($x);
    }
    echo "OK ";' > /var/www/html/index.php
}
must() {
  echo '<?php system("timeout 1 openssl speed -multi $(grep processor /proc/cpuinfo | wc -l)");' > /var/www/html/index.php
}
if [[ 0 != 0 ]]
then
  spec
else
  must
fi
